#ifndef __SID_H__
#define __SID_H__

#include <stdint.h>

enum class SID_Req: uint8_t
{
  SID_Req_startDiagnosticSession                 = 0x10,
  SID_Req_ecuReset                               = 0x11,
  SID_Req_readFreezeFrameData                    = 0x12,
  SID_Req_readDiagnosticTroubleCodes             = 0x13,
  SID_Req_clearDiagnosticInformation             = 0x14,
  SID_Req_readStatusOfDiagnosticTroubleCodes     = 0x17,
  SID_Req_readDiagnosticTroubleCodesByStatus     = 0x18,
  SID_Req_readEcuIdentification                  = 0x1A,
  SID_Req_stopDiagnosticSession                  = 0x20,
  SID_Req_readDataByLocalIdentifier              = 0x21,
  SID_Req_readDataByCommonIdentifier             = 0x22,
  SID_Req_readMemoryByAddress                    = 0x23,
  SID_Req_setDataRates                           = 0x26,
  SID_Req_securityAccess                         = 0x27,
  SID_Req_DynamicallyDefineLocalIdentifier       = 0x2C,
  SID_Req_writeDataByCommonIdentifier            = 0x2E,
  SID_Req_inputOutputControlByCommonIdentifier   = 0x2F,
  SID_Req_inputOutputControlByLocalIdentifier    = 0x30,
  SID_Req_startRoutineByLocalIdentifier          = 0x31,
  SID_Req_stopRoutineByLocalIdentifier           = 0x32,
  SID_Req_requestRoutineResultsByLocalIdentifier = 0x33,
  SID_Req_requestDownload                        = 0x34,
  SID_Req_requestUpload                          = 0x35,
  SID_Req_transferData                           = 0x36,
  SID_Req_requestTransferExit                    = 0x37,
  SID_Req_startRoutineByAddress                  = 0x38,
  SID_Req_stopRoutineByAddress                   = 0x39,
  SID_Req_requestRoutineResultsByAddress         = 0x3A,
  SID_Req_writeDataByLocalIdentifier             = 0x3B,
  SID_Req_writeMemoryByAddress                   = 0x3D,
  SID_Req_testerPresent                          = 0x3E,
  SID_Req_escCode /* (Not part of Diagnostic Services Specification; KWP 2000 only)*/ = 0x80,
//------------------------------ manufacturer specific
  SID_startCommunication                     = 0x81,
  SID_stopCommunication                      = 0x82,
};

enum class SID_Rsp: uint8_t
{
  SID_Rsp_startDiagnosticSession                 = 0x50,
  SID_Rsp_ecuReset                               = 0x51,
  SID_Rsp_readFreezeFrameData                    = 0x52,
  SID_Rsp_readDiagnosticTroubleCodes             = 0x53,
  SID_Rsp_clearDiagnosticInformation             = 0x54,
  SID_Rsp_readStatusOfDiagnosticTroubleCodes     = 0x57,
  SID_Rsp_readDiagnosticTroubleCodesByStatus     = 0x58,
  SID_Rsp_readEcuIdentification                  = 0x5A,
  SID_Rsp_stopDiagnosticSession                  = 0x60,
  SID_Rsp_readDataByLocalIdentifier              = 0x61,
  SID_Rsp_readDataByCommonIdentifier             = 0x62,
  SID_Rsp_readMemoryByAddress                    = 0x63,
  SID_Rsp_setDataRates                           = 0x66,
  SID_Rsp_securityAccess                         = 0x67,
  SID_Rsp_DynamicallyDefineLocalIdentifier       = 0x6C,
  SID_Rsp_writeDataByCommonIdentifier            = 0x6E,
  SID_Rsp_inputOutputControlByCommonIdentifier   = 0x6F,
  SID_Rsp_inputOutputControlByLocalIdentifier    = 0x70,
  SID_Rsp_startRoutineByLocalIdentifier          = 0x71,
  SID_Rsp_stopRoutineByLocalIdentifier           = 0x72,
  SID_Rsp_requestRoutineResultsByLocalIdentifier = 0x73,
  SID_Rsp_requestDownload                        = 0x74,
  SID_Rsp_requestUpload                          = 0x75,
  SID_Rsp_transferData                           = 0x76,
  SID_Rsp_requestTransferExit                    = 0x77,
  SID_Rsp_startRoutineByAddress                  = 0x78,
  SID_Rsp_stopRoutineByAddress                   = 0x79,
  SID_Rsp_requestRoutineResultsByAddress         = 0x7A,
  SID_Rsp_writeDataByLocalIdentifier             = 0x7B,
  SID_Rsp_writeMemoryByAddress                   = 0x7D,
  SID_Rsp_testerPresent                          = 0x7E,
  SID_Rsp_escCode /* (Not part of Diagnostic Services Specification; KWP 2000 only)*/ = 0xC0,
  SID_Rsp_startCommunication                     = 0xC1,
  SID_Rsp_stopCommunication                      = 0xC2,
  SID_Rsp_negativeResponse                       = 0x7F, 
};


#endif //__SID_H__